# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('results', models.ManyToManyField(related_name='search_sets', to='goat.Concept')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
