# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goat', '0003_searchresultset_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='builtin_identity_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goat.IdentitySystem'),
        ),
    ]
