# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat', '0004_authority_builtin_identity_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='namespace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
