# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat', '0006_auto_20161110_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='local_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
