# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat', '0007_concept_local_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='confidence',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
