# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat', '0009_auto_20161118_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresultset',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
